---
title: "strategy_1_stage2"
output: html_document
date: "2025-12-03"
---


```{r}
library(data.table)

# 讀資料
df <- fread("data_merged/df_m12_target.csv")

# 先排序避免混亂
df <- df[order(station, date, hour)]

```

```{r}

stations <- unique(df$station)

# 初始化
df[, inv_real := inventory]
df[, restock := 0]
df$restock_amount <- 0

# 補車參數
target_ratio <- 0.75

for (st in stations) {
  idx <- which(df$station == st)

  for (i in seq_along(idx)) {
    row_id <- idx[i]
    if (i == 1) next

    prev_id <- idx[i - 1]

    prev_inv_real <- df$inv_real[prev_id]
    net_b         <- df$net_borrow[prev_id]
    total         <- df$total[row_id]

    target_inv <- round(total * target_ratio)  # 補total* 0.75

    # 預測需求
    pred_demand <- df$net_borrow_pred[prev_id]

    # 兩大補車觸發條件
    cond_now  <- (prev_inv_real == 0)            # 當下沒車
    cond_pred <- (pred_demand >= prev_inv_real)  # 預測將借光

    if (cond_now || cond_pred) {
      if(df$inv_real[prev_id] >= target_inv) {next}
      # 🚚 補車立即生效（不延遲）
      restock_amount <- target_inv - prev_inv_real
      df$restock_amount[prev_id] <- restock_amount
      df$inv_real[row_id] <- target_inv - net_b
      df$restock[prev_id]  <- 1
    } else {
      # 正常庫存更新
      df$inv_real[row_id] <- prev_inv_real - net_b         # 不補車
    }

    # 限制庫存範圍
    df$inv_real[row_id] <- max(0, min(df$inv_real[row_id], total))
  }
}

```





```{r}

df[, borrow_earn_count := fifelse(net_borrow > 0, pmin(net_borrow, inv_real), 0)]



```

```{r}
borrow_gain <- 10
fixed_cost <- 200

a <-sum(df$borrow_earn_count)
b <- sum(df$restock)

profit = borrow_gain * a - fixed_cost * b


print(a)
print(b)
print(profit)
```




```{r}
library(readr)
write_csv(df, "df_result.csv")

```
