---
title: "strategy_default_stage2"
output: html_document
date: "2025-12-03"
---


```{r}
library(data.table)

# 讀資料
df <- fread("data_merged/df_m12_target.csv")

# 先排序避免混亂
df <- df[order(station, date, hour)]

```


# 更新 inventory
```{r}
stations <- unique(df$station)

for (st in stations) {
  idx <- which(df$station == st)

  # 逐小時更新
  for (i in seq_along(idx)) {
    row_id <- idx[i]
  
    if (i == 1) {
      # 第一筆資料直接沿用原始 inventory，不做判斷
      next
    }
  
    prev_id <- idx[i - 1]
  
    prev_inv <- df$inventory[prev_id]       # 上一小時（已更新）庫存
    net_b    <- df$net_borrow[prev_id]       # 上一小時到這一小時間的淨借車
    total    <- df$total[row_id]            # 固定總車位數
  
    # ----------------------
    # 補車邏輯
    # ----------------------
   
    # 正常狀態 → 使用上一小時的庫存減本小時 net_borrow
    df$inventory[row_id] <- prev_inv - net_b
  }
}

```






# 創造inve_real, restock
```{r}




# 初始化欄位
df[, inv_real := inventory]
df[, restock := 0]  # 是否補車（0/1）

# 補車參數

target_ratio <- 0.75    # 補到此比率

for (st in stations) {
  idx <- which(df$station == st)

  for (i in seq_along(idx)) {
    row_id <- idx[i]
    if (i == 1) next

    prev_id <- idx[i - 1]

    prev_inv <- df$inv_real[prev_id]
    total    <- df$total[row_id]
    net_b    <- df$net_borrow[prev_id]

    safety_threshold <- 0
    target_inv       <- round(total * target_ratio)

    # 如果上一小時庫存太低 → 補車（補到目標量）
    if (prev_inv <= safety_threshold) {
      df$inv_real[row_id] <- target_inv - net_b
      df$restock[row_id]   <- 1
    } else {
      # 正常庫存更新
      df$inv_real[row_id] <- prev_inv - net_b
    }

    # 防護：庫存範圍 0 ~ total
    df$inv_real[row_id] <- max(0, min(df$inv_real[row_id], total))
  }
}


```



```{r}

df[, borrow_earn_count := fifelse(net_borrow > 0, pmin(net_borrow, inv_real), 0)]



```

```{r}



borrow_gain <- 10
fixed_cost <- 200

a <-sum(df$borrow_earn_count)
b <- sum(df$restock)

profit = borrow_gain * a - fixed_cost * b


print(a)
print(b)
print(profit)
```


```{r}



borrow_gain <- 10
fixed_cost <- 200

a <-93343
b <-2526

profit = borrow_gain * a - fixed_cost * b


print(a)
print(b)
print(profit)
```
